apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-test-app
  template:
    metadata:
      labels:
        app: flask-test-app
    spec:
      containers:
      - name: flask-test-app
        image: paffy/weather-app
        env:
            - 
              name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: GOOGLE_CLIENT_ID
            - 
              name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: GOOGLE_CLIENT_SECRET
            -
              name: API
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: API
            -
              name: API_DATE
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: API_DATE
        ports:
        - containerPort: 5000

